language: elixir
elixir:
  - 1.10
otp_release:
  - 21.0
services: docker
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps

stages:
  - build docker image
  - test

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t conference_service .
        - docker images
        - docker tag conference_service $DOCKER_USERNAME/conference
        - docker push $DOCKER_USERNAME/conference
    - stage: test
      install:
        - docker-compose up -d
        - mix local.hex --force
        - mix local.rebar --force
      script:
        - mix git_hooks.run all
        - docker-compose down