os: linux
language: elixir
elixir:
  - 1.10
otp_release:
  - 23.0.2
services: 
  - docker
cache:
  directories:
    - _build
    - deps

stages:
  - build docker image
  - test

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t conference_service .
        - docker images
        - docker tag conference_service $DOCKER_USERNAME/conference
        - docker push $DOCKER_USERNAME/conference
    - stage: test
      install:
        - mix local.hex --force
        - mix local.rebar --force
        - docker-compose up -d
      script:
        - mix test
        - docker-compose down