language: elixir
elixir: '1.10'
sudo: false
otp_release:
  - 20
env:
  global:
    - HEX_USERNAME=conf
    # Follow other language's environment
    # e.g.) `RACK_ENV=test` has been setted as Default Environment Variables
    # https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
script:
  - mix git_hooks.run all
deploy:
  # https://docs.travis-ci.com/user/deployment/script/
  # > `script` must be a scalar pointing to an executable file or command.
  provider: script
  # http://yaml.org/spec/1.2/spec.html#id2779048
  # `>-` indicates the line folding.
  script: >-
    mix deps.get &&
    mix hex.publish --yes &&
    git clean -f
  on:
    tags: true