language: elixir
elixir:
  - 1.10
otp_release:
  - 21.0
services: docker
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
before_script:
  - echo "Before Script:"
  - docker-compose up --build -d
script:
  - mix git_hooks.run all
after_script:
  - docker tag conference-service kedith/conference
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kedith/conference
  - docker-compose down