language: elixir
elixir:
  - 1.10
otp_release:
  - 21.0
services: docker
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps

stages:
  - build docker image
  - test
  - deploy

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t conference_service .
        - docker images
        - docker tag conference_service $DOCKER_USERNAME/conference
        - docker push $DOCKER_USERNAME/conference
    - stage: test
      install:
        - docker-compose up -d
        - mix local.hex --force
      script:
        - mix git_hooks.run all
        - docker-compose down
    - stage: deploy
      install:
        - AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        - sudo apt-get install apt-transport-https
        - sudo apt-get update && sudo apt-get install azure-cli
      script:
        - az login --service-principal -u $AZURE_SERVICE_PRINCIPAL -p $AZURE_SERVICE_PRINCIPAL_PASSWORD --tenant $AZURE_TENANT
        - az webapp config container set --resource-group $AZURE_RESOURCE_GROUP --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml
