version: '3.7'

services:
  postgres:
    image: postgres:12.0
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: conference_test

volumes:
  postgres-data: