version: '3.7'

services:
  web:
    container_name: conference-service
    image: kedith/conference:simple
    restart: always
    ports:
      - "4004:4000"
    depends_on:
      - database
  database:
    container_name: db
    image: postgres:11.0
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/database
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'Conference'
      PGDATA: '/var/lib/postgresql/data'
volumes:
  db-data: