version: '3.7'

services:
  web:
    container_name: conference-service
    build: .
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - database
  database:
    container_name: db
    image: postgres:11.0
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/database
    env_file:
      - postgres-variables.env

volumes:
  db-data: