version: '3.7'

services:
  conference:
    container_name: conference-service
    image: kedith/conference:latest
    restart: always
    ports:
      - 4004:4000
    depends_on:
      - confDb
  user:
    image: kedith/user-conference:latest
    container_name: user-service
    ports:
      - 4005:4000
    depends_on:
      - userDb
  confDb:
    container_name: db
    image: postgres:11.0
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/confDb
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "Conference"
      PGDATA: "/var/lib/postgresql/data"
  userDb:
    image: postgres:11.0
    container_name: userDb
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "User"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - data-volume:/var/lib/userDb
  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.1
    volumes: 
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5601:5601
volumes:
  db-data:
  data-volume:

